const Roles = [
    "Backend",
    "Frontend",
    "Fullstack",
    "IOS",
    "Flutter",
    "React Native",
    "Android",
    "Tech Lead",
    "Dev-Ops",
    "Data Engineer",
    "Data Science",
    "Computer-Vision",
    "Nlp",
    "Test/Qa",
    "Web3",
    "Deep-Learning",
    "Sre",
    "Data-Infrastructure",
    "Designer",
    "Design MAnager",
    "Graphic Designer",
    "Product Designer",
    "Product Manager",
    "Operations Manager",
    "Founder's Office/Chief Of Staff",
    "Sales Development Representative",
    "Account Executive",
    "Account Manager",
    "Digital Marketing Manager",
    "Growth Hacker",
    "Marketing",
    "Product Marketing Manager",
    "HardWare",
    "Mechanical",
    "Systems",
    "Business Analyst",
    "Data Analyst",
    "Project Manager",
    "Management",
    "Legal",
    "Hr",
    "Finance",
];

const Location = ["Remote", "Hybrid", "In-office"];

const Tech = [
    "Python",
    "GoLang",
    "Ruby/Rails",
    "Kotlin",
    "Django",
    "C#",
    "GraphQL",
    "Flask",
    "Typescript",
    "AWS",
    "Javascript",
    "Rust",
    "NodeJS",
    "React",
];

const MinPay = ["0L", "10L", "20L", "30L", "40L", "50L", "60L", "70L"];
const Experience = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

const getFilterCategory = {
    Roles: "roles",
    Location: "location",
    Tech: "tech",
    "Minimum Pay": "minimumPay",
    Company: "companyName",
    Experience: "experience",
    "No. of Employees": "numberOfEmployees",
};

export {
    Roles,
    MinPay,
    Tech,
    Location,
    getFilterCategory,
    Experience,
};
